#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 27 06:52:02 UYT 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=Fantasy Shaders Reimagined v1.0.1.zip
