[general]
	# Default: 1
	# Range: 1 ~ 2
	defaultPixelScale = 1
	keyboardLayout = "US_QWERTY"
	animationsEnabled = true
	hiddenBindingsEnabled = true
	categoriesEnabled = true
	fKeysEnabled = false
	allKeysEnabled = true
	alternatingLineColorsEnabled = true
	# Default: 0.4000000059604645
	# Range: 0.0 ~ 1.0
	panelOpacity = 0.4000000059604645
	# Default: 3
	# Range: 1 ~ 20
	maxUnhoveredAssignments = 3

[filters]
	hiddenBindingLabels = """
1
2
3
4
5
6
7
8
9
W
T
A
S
D
/"""
	disabledMods = ""
	disabledBindings = ""

[categories]
	presetCategoryColors = """
crimson|Crimson|#B63C47FF
purple|Purple|#9145D6FF
emerald|Emerald|#1F9F4DFF
tangerine|Tangerine|#F97316FF
amber|Amber|#F59E0BFF
cyan|Cyan|#06B6D4FF
rose|Rose|#EC4899FF
lime|Lime|#84CC16FF
teal|Teal|#14B8A6FF
copper|Copper|#B45309FF"""
	customCategories = """
combat|Combat|#B63C47FF|#FFFFFFFF
magic|Magic|#9145D6FF|#FFFFFFFF
movement|Movement|#1F9F4DFF|#FFFFFFFF
building|Building|#F59E0BFF|#111318FF
utility|Utility|#F97316FF|#FFFFFFFF
technology|Technology|#06B6D4FF|#FFFFFFFF"""
	keyCategoryAssignments = ""

[colors]
	# Default: -16686644
	# Range: > -2147483648
	keyAssignedFill = -16686644
	# Default: -13684426
	# Range: > -2147483648
	keyUnusedFill = -13684426
	# Default: -14737115
	# Range: > -2147483648
	keyHiddenFill = -14737115
	# Default: -10570753
	# Range: > -2147483648
	keyHoverFill = -10570753
	# Default: -1
	# Range: > -2147483648
	keyAssignedText = -1
	# Default: -6380888
	# Range: > -2147483648
	keyUnusedText = -6380888
	# Default: -4868683
	# Range: > -2147483648
	keyHiddenText = -4868683
	# Default: -3090208
	# Range: > -2147483648
	keyHoverText = -3090208
	# Default: -12960446
	# Range: > -2147483648
	boxFill = -12960446
	# Default: -12104878
	# Range: > -2147483648
	boxHoverFill = -12104878
	# Default: -15000544
	# Range: > -2147483648
	boxBorder = -15000544
	# Default: -9262869
	# Range: > -2147483648
	boxHoverBorder = -9262869
	# Default: -1710619
	# Range: > -2147483648
	boxText = -1710619
	# Default: -6314578
	# Range: > -2147483648
	boxSourceText = -6314578
	# Default: -15066080
	# Range: > -2147483648
	keyboardFill = -15066080
	# Default: -15921648
	# Range: > -2147483648
	keyboardBorder = -15921648
	# Default: -7696490
	# Range: > -2147483648
	lineDefault = -7696490
	# Default: -10723224
	# Range: > -2147483648
	lineDefaultAlt = -10723224
	# Default: -7947009
	# Range: > -2147483648
	lineHover = -7947009
